/**
 * Auto-CRUD Route Generator
 *
 * Generates standard REST routes from Model definitions:
 *   GET    /v1/{type}s       → list (scoped, paginated, sortable)
 *   GET    /v1/{type}s/:id   → get one (scoped)
 *   POST   /v1/{type}s       → create (scoped)
 *   PUT    /v1/{type}s/:id   → update (scoped)
 *   DELETE /v1/{type}s/:id   → delete (scoped)
 *   PATCH  /v1/{type}s/:id   → atomic JSON Patch (scoped)
 *
 * Extracted from Dollhouse Studio's adapters/routes.ts (373 lines).
 *
 * Route-priority contract
 * Every auto-CRUD route is registered with `priority: AUTO_CRUD_PRIORITY`
 * (200), which is intentionally HIGHER than the framework's default
 * priority (100) used by user-written controllers. Lower numbers sort
 * first in `getRoutes()`, so user routes attach to polka before
 * auto-CRUD when both register the same prefix.
 *
 * Without this gap, a user controller like
 *
 *   route.get("/v1/sources/providers", ...)
 *
 * would be shadowed by the auto-CRUD `GET /v1/sources/:id` (which
 * registers at boot step 12, before custom controllers are discovered
 * at step 13). The shadow turned the literal segment `"providers"`
 * into an attempted Source id lookup, which 404'd as `"source not
 * found"` — invisible at the user's call site. The priority gap moves
 * the resolution rule out of "whoever registered first" and into
 * "explicit routes always win," which is what every framework user
 * already expects.
 *
 * Users who deliberately set a priority outside the [0, 199] band keep
 * that ordering — the gap only changes the DEFAULT for auto-CRUD.
 */

import type { ModelConstructor, ScopeContext } from "@parcae/model";
import { Model } from "@parcae/model";
import pluralize from "pluralize";
import { ClientError, json, notFound, forbidden } from "../helpers";
import { log } from "../logger";
import { route } from "../routing/route";
import {
  prepareClientQuery,
  runQuerySubscription,
  runQueryStatic,
} from "../services/query-subscription";
import type { BackendAdapter } from "./model";

// ─── Constants ───────────────────────────────────────────────────────────────

/**
 * Priority bucket every auto-CRUD route is registered into. Higher
 * number = LOWER precedence in `getRoutes()`'s ascending sort, so user
 * routes (default `priority: 100`) attach to polka first and shadow
 * the framework-generated `:id` patterns. See the module header for
 * the full rationale.
 */
const AUTO_CRUD_PRIORITY = 200;

// ─── Helpers ─────────────────────────────────────────────────────────────────

function buildScopeContext(req: any, res: any): ScopeContext {
  return {
    user: req.session?.user ?? null,
    params: req.params ?? {},
    data: req.body ?? {},
  };
}

function resolvePath(modelClass: ModelConstructor, version: string): string {
  if (modelClass.path) return modelClass.path;
  return `/${version}/${pluralize(modelClass.type)}`;
}

/**
 * System fields the framework always controls — never client-writable
 * through HTTP. The `id` is generated by `Model.create`; the timestamps
 * are stamped by the adapter; `type` is the model's discriminator. A
 * client overriding any of these would be a correctness bug, not just
 * a security one.
 */
const SYSTEM_FIELDS: ReadonlySet<string> = new Set([
  "id",
  "createdAt",
  "updatedAt",
  "type",
]);

/**
 * Build the full deny-list for a model's HTTP write paths — system
 * fields plus the subclass's `static readonlyFields`. Both are
 * read-only frozen at boot, so we can derive this once per model and
 * cache on the model class. Used by POST / PUT bodies and by the
 * PATCH ops first-segment check.
 */
const READONLY_CACHE = new WeakMap<ModelConstructor, ReadonlySet<string>>();

function readonlyFieldsFor(modelClass: ModelConstructor): ReadonlySet<string> {
  const cached = READONLY_CACHE.get(modelClass);
  if (cached) return cached;
  const merged = new Set(SYSTEM_FIELDS);
  if (modelClass.readonlyFields) {
    for (const f of modelClass.readonlyFields) merged.add(f);
  }
  READONLY_CACHE.set(modelClass, merged);
  return merged;
}

function queryStringValue(value: unknown): string {
  const raw = Array.isArray(value) ? value[0] : value;
  return typeof raw === "string" ? raw : "";
}

function assertNumericColumn(modelClass: ModelConstructor, column: string): void {
  const type = modelClass.__schema?.[column];
  if (type !== "integer" && type !== "number") {
    throw new ClientError(`Invalid numeric column "${column}"`);
  }
}

/**
 * Strip framework-protected and model-protected fields from a client
 * body before they get mass-assigned onto a model instance. Returns
 * a fresh object so the caller's `req.body` isn't mutated.
 */
function stripReadonly(
  modelClass: ModelConstructor,
  data: Record<string, any>,
): Record<string, any> {
  const deny = readonlyFieldsFor(modelClass);
  const out: Record<string, any> = {};
  for (const [key, value] of Object.entries(data)) {
    if (deny.has(key)) continue;
    out[key] = value;
  }
  return out;
}

/**
 * Loose Model-instance shape for the route handlers. Auto-CRUD
 * routes look up rows via `adapter.query(...).first()` whose generic
 * is `any`; we project the methods we actually call on the result so
 * each handler doesn't have to cast individually.
 */
interface RouteModelRow {
  id: string;
  __data: Record<string, any>;
  save(): Promise<void>;
  remove(): Promise<void>;
  sanitize?(user?: { id: string }): Record<string, any> | Promise<Record<string, any>>;
  [field: string]: unknown;
}

/**
 * Look up a row by `:id` parameter, falling back to `tmp` so
 * optimistic-create flows (client generates a `tmp` id, then the
 * server-assigned `id` lands on the next refresh) keep working. The
 * scope predicate is applied to both lookups so a client can't
 * escape access control by routing through tmp.
 *
 * Returns `null` when nothing matches — the caller produces the 404.
 * Extracted from the GET-one / PUT / DELETE / PATCH handlers, which
 * all run this exact two-step query.
 */
async function findByIdOrTmp(
  adapter: BackendAdapter,
  ModelClass: ModelConstructor,
  paramId: string,
  scopeResult: any,
): Promise<RouteModelRow | null> {
  let item = await adapter
    .query(ModelClass)
    .select("*")
    .where("id", paramId)
    .where(scopeResult)
    .first();
  if (!item) {
    item = await adapter
      .query(ModelClass)
      .select("*")
      .where("tmp", paramId)
      .where(scopeResult)
      .first();
  }
  return (item as RouteModelRow | null) ?? null;
}

/**
 * Project a model instance into the wire shape for a route response.
 * Honours the subclass's `sanitize()` (which honours `privateFields`
 * by default after the latest Model changes); falls back to
 * `__data` for any row that somehow lacks `sanitize` (defensive —
 * with the Model default in place this is effectively unreachable).
 */
async function projectForWire(
  item: RouteModelRow,
  user: { id: string } | null | undefined,
): Promise<Record<string, any>> {
  if (typeof item.sanitize === "function") {
    return item.sanitize(user ?? undefined);
  }
  return item.__data;
}

/**
 * Centralised error responder. Maps `ClientError` to its declared
 * status code (typically 400/403/409) and anything else to a 500
 * with a generic message so internal details don't leak to the
 * client. Caller picks the `where` label that goes into the server
 * log line for triage.
 */
function respondWithError(
  res: any,
  err: unknown,
  where: string,
): void {
  if (err instanceof ClientError) {
    json(res, err.status, {
      result: null,
      success: false,
      error: err.message,
    });
    return;
  }
  log.error(`[routes] ${where} error:`, err);
  json(res, 500, {
    result: null,
    success: false,
    error: "An error occurred while processing your request",
  });
}

// ─── Route Generator ─────────────────────────────────────────────────────────

/**
 * Register auto-CRUD routes for all models that have scopes defined.
 */
export function registerModelRoutes(
  models: ModelConstructor[],
  adapter: BackendAdapter,
  version = "v1",
): number {
  let count = 0;

  // Build a type → ModelConstructor index once for the whole batch.
  // `validateExpandSpecs` accepts this so the LIST handler can
  // resolve a ref's target without coupling to BackendAdapter's
  // private `_models` map. Frozen — registration runs once at boot.
  const modelByType = new Map<string, ModelConstructor>();
  for (const M of models) {
    if (M.type) modelByType.set(M.type, M);
  }

  for (const ModelClass of models) {
    const scope = ModelClass.scope;
    if (!scope) continue;

    const path = resolvePath(ModelClass, version);
    const type = ModelClass.type;

    // ── GET /path — list ───────────────────────────────────────────

    if (scope.read) {
      route.get(path, async (req: any, res: any) => {
        const ctx = buildScopeContext(req, res);
        const scopeResult = scope.read!(ctx);
        if (!scopeResult) return forbidden(res);

        const data = req.query || {};
        const rawSteps = data.__query ?? [];

        try {
          const prep = prepareClientQuery({
            ModelClass,
            scopeResult,
            rawSteps,
            modelByType,
            adapter,
          });

          if (data.__count === "true" || data.__count === true) {
            const total = await prep.query.count();
            return json(res, 200, { result: { total }, success: true });
          }

          const sumColumn = queryStringValue(data.__sum);
          if (sumColumn) {
            assertNumericColumn(ModelClass, sumColumn);
            const total = await prep.query.sum(sumColumn);
            return json(res, 200, { result: { total }, success: true });
          }

          // `__subscribe: false` is the client's static-query opt-out
          // — set by `useQuery({ subscribe: false })` and `prefetch(...,
          // { subscribe: false })`. The wire request short-circuits
          // the subscribe branch below, falls through to
          // `runQueryStatic`, and the response omits `__queryHash`
          // so the SDK never attaches a `query:${hash}` listener.
          const wantsSubscription = !(
            data.__subscribe === false || data.__subscribe === "false"
          );

          // Socket-RPC LIST → subscribe to query-level change
          // notifications. The subscription manager re-evals on model
          // changes and emits surgical add/remove/update ops to this
          // socket. `__forceRefresh: true` is the client's drift-poll
          // hook — periodic refetches set it so we re-execute the
          // cached query against the DB and emit any drift ops to
          // every subscriber on the same hash. Without it, repeated
          // LIST calls just hand back the cached row set.
          const socketId = req._socketId;
          if (socketId && adapter.subscriptions && wantsSubscription) {
            const force =
              data.__forceRefresh === true || data.__forceRefresh === "true";
            const { items, hash, totalCount } = await runQuerySubscription({
              prep,
              socketId,
              user: ctx.user ?? null,
              adapter,
              force,
            });

            json(res, 200, {
              result: {
                total: items.length,
                totalCount,
                __queryHash: hash,
                [pluralize(type)]: items,
              },
              success: true,
            });
            return;
          }

          // Static path — no subscription, no realtime. Used for the
          // non-socket fetch fallback and for socket requests that
          // opted out via `__subscribe: false`. The pipeline (plain
          // find + sanitise + expand hydrate) is shared with the
          // socket-RPC resync handler so the two paths can't drift
          // apart again.
          const { items, totalCount } = await runQueryStatic({
            prep,
            user: ctx.user ?? null,
            adapter,
          });

          json(res, 200, {
            result: {
              total: items.length,
              totalCount,
              [pluralize(type)]: items,
            },
            success: true,
          });
        } catch (err) {
          respondWithError(res, err, `GET ${path}`);
        }
      }, { priority: AUTO_CRUD_PRIORITY });
      count++;
    }

    // ── GET /path/:id — get one ────────────────────────────────────

    if (scope.read) {
      route.get(`${path}/:id`, async (req: any, res: any) => {
        try {
          const ctx = buildScopeContext(req, res);
          const scopeResult = scope.read!(ctx);
          if (!scopeResult) return forbidden(res);

          const item = await findByIdOrTmp(
            adapter,
            ModelClass,
            req.params.id,
            scopeResult,
          );
          if (!item) return notFound(res, type);

          json(res, 200, {
            result: await projectForWire(item, ctx.user),
            success: true,
          });
        } catch (err) {
          respondWithError(res, err, `GET ${path}/:id`);
        }
      }, { priority: AUTO_CRUD_PRIORITY });
      count++;
    }

    // ── POST /path — create ────────────────────────────────────────

    if (scope.create) {
      route.post(path, async (req: any, res: any) => {
        try {
          const ctx = buildScopeContext(req, res);
          const scopeData = scope.create!(ctx);
          if (!scopeData) return forbidden(res);

          // 1. Strip readonly fields from the client body — counters,
          //    ownership refs, state-machine cols (see Model.readonlyFields).
          // 2. Merge in the scope-provided overrides last so a malicious
          //    body can't override e.g. `user: ctx.user.id`.
          const body = stripReadonly(ModelClass, req.body || {});
          const data = { ...body, ...scopeData };
          const item = Model.create.call(
            ModelClass,
            data,
          ) as unknown as RouteModelRow;
          await item.save();

          json(res, 201, {
            result: await projectForWire(item, ctx.user),
            success: true,
          });
        } catch (err) {
          respondWithError(res, err, `POST ${path}`);
        }
      }, { priority: AUTO_CRUD_PRIORITY });
      count++;
    }

    // ── PUT /path/:id — update ─────────────────────────────────────

    if (scope.update) {
      route.put(`${path}/:id`, async (req: any, res: any) => {
        try {
          const ctx = buildScopeContext(req, res);
          const scopeResult = scope.update!(ctx);
          if (!scopeResult) return forbidden(res);

          const item = await findByIdOrTmp(
            adapter,
            ModelClass,
            req.params.id,
            scopeResult,
          );
          if (!item) return notFound(res, type);

          // Strip readonly fields BEFORE mass-assigning. The framework
          // protects id/createdAt/updatedAt/type unconditionally; per-
          // model `static readonlyFields` adds counter columns,
          // ownership refs, and state-machine cols on top.
          const data = stripReadonly(ModelClass, req.body || {});
          for (const [key, value] of Object.entries(data)) {
            item[key] = value;
          }

          await item.save();

          json(res, 200, {
            result: await projectForWire(item, ctx.user),
            success: true,
          });
        } catch (err) {
          respondWithError(res, err, `PUT ${path}/:id`);
        }
      }, { priority: AUTO_CRUD_PRIORITY });
      count++;
    }

    // ── DELETE /path/:id — delete ──────────────────────────────────

    if (scope.delete) {
      route.delete(`${path}/:id`, async (req: any, res: any) => {
        try {
          const ctx = buildScopeContext(req, res);
          const scopeResult = scope.delete!(ctx);
          if (!scopeResult) return forbidden(res);

          const item = await findByIdOrTmp(
            adapter,
            ModelClass,
            req.params.id,
            scopeResult,
          );
          if (!item) return notFound(res, type);

          await item.remove();

          json(res, 200, { result: { id: req.params.id }, success: true });
        } catch (err) {
          respondWithError(res, err, `DELETE ${path}/:id`);
        }
      }, { priority: AUTO_CRUD_PRIORITY });
      count++;
    }

    // ── PATCH /path/:id — atomic JSON Patch ────────────────────────

    if (scope.patch || scope.update) {
      route.patch(`${path}/:id`, async (req: any, res: any) => {
        try {
          const ctx = buildScopeContext(req, res);
          const scopeResult = (scope.patch ?? scope.update)!(ctx);
          if (!scopeResult) return forbidden(res);

          const data = req.body || {};
          if (!Array.isArray(data.ops) || data.ops.length === 0) {
            return json(res, 400, {
              result: null,
              success: false,
              error: "ops array required",
            });
          }

          // Reject the whole batch if any op targets a readonly
          // column — fail loud rather than silently dropping ops so
          // the client knows its expected mutation didn't apply.
          // The first path segment is the column (RFC 6902 paths
          // start with `/`, then column, then optional inner JSON
          // path); only top-level reads are protected.
          const deny = readonlyFieldsFor(ModelClass);
          for (const op of data.ops) {
            if (!op?.path || typeof op.path !== "string") continue;
            const column = op.path.slice(1).split("/")[0];
            if (column && deny.has(column)) {
              return json(res, 403, {
                result: null,
                success: false,
                error: `Field "${column}" is read-only`,
              });
            }
          }

          const item = await findByIdOrTmp(
            adapter,
            ModelClass,
            req.params.id,
            scopeResult,
          );
          if (!item) return notFound(res, type);

          await adapter.patch(item, data.ops);

          json(res, 200, {
            result: await projectForWire(item, ctx.user),
            success: true,
          });
        } catch (err) {
          respondWithError(res, err, `PATCH ${path}/:id`);
        }
      }, { priority: AUTO_CRUD_PRIORITY });
      count++;
    }
  }

  return count;
}
