/**
 * @parcae/model — Adapter Types
 *
 * Defines the adapter interface that decouples Model from persistence.
 * Frontend: EventEmitter + transport
 * Backend: Knex + PostgreSQL
 */

import type { Operation as PatchOp } from "fast-json-patch";

// ─── Column Types ────────────────────────────────────────────────────────────

/**
 * Primitive column types that map to Postgres column types.
 * These are resolved from TypeScript types via ts-morph at startup.
 */
export type PrimitiveColumnType =
  | "string" // VARCHAR(2048)
  | "text" // TEXT
  | "integer" // INTEGER
  | "number" // DOUBLE PRECISION
  | "boolean" // BOOLEAN
  | "datetime" // TIMESTAMP
  | "json"; // JSONB

/**
 * A column can be a primitive type or a reference to another Model class.
 */
export type ColumnType =
  | PrimitiveColumnType
  | { kind: "ref"; target: ModelConstructor };

/**
 * Schema definition for a model, mapping property names to column types.
 * Generated by the ts-morph schema resolver at startup.
 */
export type SchemaDefinition = Record<string, ColumnType>;

/**
 * Index definition — a single column name or a composite index.
 */
export type IndexDefinition = string | string[];

// ─── Model Constructor ───────────────────────────────────────────────────────

/**
 * The static side of a Model subclass — metadata + the `new` signature
 * adapters and schema generators need to introspect the class.
 *
 * Static query/builder methods (`where`, `whereIn`, `find`, …) live on
 * the `Model` class itself (see `../Model.ts`) and ARE typed properly
 * when called against a concrete subclass like `Scene.where(...)`.
 * Generic helpers that take a model-class parameter should use the
 * `ModelClass<T>` alias below, which captures both the metadata
 * surface AND the typed static query methods.
 */
export interface ModelConstructor<T = any> {
  type: string;
  path?: string;
  scope?: ModelScope;
  indexes?: IndexDefinition[];
  managed?: boolean;
  /**
   * Fields to index for full-text and fuzzy search.
   * When present, `ensureTable()` creates:
   * - A generated `_search` tsvector column + GIN index
   * - Per-field trigram GIN indexes (pg_trgm)
   * - On AlloyDB: `_embedding` vector(768) column + ScaNN index
   *
   * Fields are weighted by order: first = 'A' (highest), second = 'B', etc.
   *
   * @example
   * ```typescript
   * class Project extends Model {
   *   static searchFields = ["title", "description"];
   * }
   * // Then query with: Project.search("ghost town").find()
   * ```
   */
  searchFields?: string[];
  /**
   * Field-level write protection. Listed columns are stripped from
   * client request bodies before being applied to the model in the
   * auto-CRUD `POST` / `PUT` / `PATCH` routes. Server-side code can
   * still write these fields directly.
   *
   * Default (empty) means only the framework's hardcoded system
   * fields (`id`, `createdAt`, `updatedAt`, `type`) are protected.
   */
  readonlyFields?: readonly string[];
  /**
   * Field-level read protection. Listed columns are stripped from
   * the default `sanitize()` projection so a column like
   * `passwordHash` / `apiKey` / `inviteToken` doesn't leak through
   * auto-CRUD GET endpoints.
   *
   * Subclasses that override `sanitize()` directly bypass this list.
   * Default (empty) means every column is included.
   */
  privateFields?: readonly string[];
  __schema?: SchemaDefinition;
  new (adapter: ModelAdapter, data?: Record<string, any>): T;
}

/**
 * Typed "model class" surface for generic helper functions.
 *
 *   async function hydrateTop<R extends Model & { id: string }>(
 *     ModelClass: ModelClass<R>,
 *     ids: string[],
 *   ) {
 *     const rows = await ModelClass.whereIn("id", ids).find()
 *     // ↑ Typed as Promise<R[]> — no `as any` needed.
 *     return rows
 *   }
 *
 * Combines `ModelConstructor<T>` (for adapter / schema use) with the
 * static query methods every Model subclass inherits. Return types
 * mirror the class statics so concrete calls (`Scene.where(...)`) and
 * generic calls (`ModelClass.where(...)`) produce the same chain.
 */
export interface ModelClass<T> extends ModelConstructor<T> {
  create(data?: Record<string, any>): T;
  findById(id: string): Promise<T | null>;
  where(...args: any[]): QueryChain<T>;
  whereRaw(query: string, ...bindings: any[]): QueryChain<T>;
  whereIn(column: string, values: any[]): QueryChain<T>;
  whereNot(...args: any[]): QueryChain<T>;
  whereNotIn(column: string, values: any[]): QueryChain<T>;
  whereNull(column: string): QueryChain<T>;
  whereNotNull(column: string): QueryChain<T>;
  select(...columns: string[]): QueryChain<T>;
  count(): Promise<number>;
  search(term: string): QueryChain<T>;
}

// ─── Scope System ────────────────────────────────────────────────────────────

/**
 * Context passed to scope functions. Contains the authenticated user
 * and request parameters.
 */
export interface ScopeContext {
  user?: { id: string; [key: string]: any } | null;
  params?: Record<string, string>;
  data?: Record<string, any>;
}

/**
 * The result of a scope function. Either:
 * - A query builder modifier function (for read/update/delete/patch)
 * - A data object to merge (for create — e.g. { user: ctx.user.id })
 * - null to deny access
 */
export type ScopeResult = ((qb: any) => any) | Record<string, any> | null;

/**
 * A scope function receives the request context and returns a ScopeResult.
 */
export type ScopeFunction = (ctx: ScopeContext) => ScopeResult;

/**
 * Per-operation scope definitions.
 */
export interface ModelScope {
  read?: ScopeFunction;
  create?: ScopeFunction;
  update?: ScopeFunction;
  delete?: ScopeFunction;
  patch?: ScopeFunction;
}

// ─── Query Chain ─────────────────────────────────────────────────────────────

/**
 * A serializable query step. On the frontend, query chains record steps
 * as these objects and send them to the backend for execution.
 */
export interface QueryStep {
  method: string;
  args: any[];
}

/**
 * Chainable query builder. The generic T flows through to terminal methods.
 *
 * On the backend, each method directly mutates a Knex query.
 * On the frontend, each method records a QueryStep for serialization.
 */
export interface QueryChain<T> {
  // Chainable — filtering
  where(...args: any[]): QueryChain<T>;
  andWhere(...args: any[]): QueryChain<T>;
  orWhere(...args: any[]): QueryChain<T>;
  whereIn(column: string, values: any[]): QueryChain<T>;
  whereNot(...args: any[]): QueryChain<T>;
  whereNotIn(column: string, values: any[]): QueryChain<T>;
  whereNull(column: string): QueryChain<T>;
  whereNotNull(column: string): QueryChain<T>;
  whereBetween(column: string, range: [any, any]): QueryChain<T>;
  whereRaw(query: string, ...bindings: any[]): QueryChain<T>;
  orWhereRaw(query: string, ...bindings: any[]): QueryChain<T>;
  orWhereIn(column: string, values: any[]): QueryChain<T>;
  orWhereNull(column: string): QueryChain<T>;
  whereExists(callback: any): QueryChain<T>;

  // Chainable — search
  /**
   * Full-text + fuzzy search across fields declared in `static search`.
   * On the backend, generates hybrid SQL (tsvector + trigram + optional vector).
   * On the frontend, records a QueryStep for serialization.
   */
  search(term: string): QueryChain<T>;

  // Chainable — ordering & pagination
  /**
   * Order the result set.
   *
   *   .orderBy("createdAt", "desc")
   *
   * # Opt out of order entirely — `.orderBy(false)`
   *
   * The subscriptions manager normally ships an `order: string[]`
   * field on the wire envelope whenever the ordered id list
   * changes. For queries whose consumers don't care about ordering
   * (set membership only — the client looks up models by id /
   * path), that's wasted bytes AND causes the client's items array
   * reference to flip whenever Postgres returns rows in a different
   * heap order after an UPDATE.
   *
   * Pass `false` instead of a column name to:
   *   - Skip ORDER BY in the SQL.
   *   - Tell the subscriptions manager to omit `order` from the
   *     envelope entirely.
   *   - Make the client's `useQuery` never run `reorderByIds`, so
   *     the items reference stays stable across pure-scalar patches.
   *
   * `.orderBy(false)` and `.orderBy(column, dir)` are mutually
   * exclusive within one chain — the last call wins. Default is
   * "emit order" for back-compat.
   */
  orderBy(column: string, direction?: "asc" | "desc"): QueryChain<T>;
  orderBy(emit: false): QueryChain<T>;
  orderByRaw(query: string, ...bindings: any[]): QueryChain<T>;
  limit(count: number): QueryChain<T>;
  offset(count: number): QueryChain<T>;

  // Chainable — selection & grouping
  select(...columns: string[]): QueryChain<T>;
  distinct(...columns: string[]): QueryChain<T>;
  distinctOn(...columns: string[]): QueryChain<T>;
  groupBy(...columns: string[]): QueryChain<T>;
  groupByRaw(query: string, ...bindings: any[]): QueryChain<T>;
  having(...args: any[]): QueryChain<T>;
  havingRaw(query: string, ...bindings: any[]): QueryChain<T>;

  // Chainable — joins
  join(...args: any[]): QueryChain<T>;
  innerJoin(...args: any[]): QueryChain<T>;
  leftJoin(...args: any[]): QueryChain<T>;
  rightJoin(...args: any[]): QueryChain<T>;

  // Chainable — modifiers
  clearOrder(): QueryChain<T>;
  clearSelect(): QueryChain<T>;
  clearLimit(): QueryChain<T>;
  from(table: string): QueryChain<T>;

  /**
   * Inline named ref fields in the LIST response, batched on the
   * backend via the request-scoped `RefLoader`.
   *
   * Without `.expand(...)`, ref columns serialize as raw id strings;
   * the client has to round-trip `findById` per row to paint anything.
   * That's the canonical N+1 — one `GET /v1/files/:id` per asset on
   * editor mount.
   *
   * Two shapes:
   *
   *     .expand("file")              // full linked row inlined
   *     .expand("file.url")          // single field projected
   *     .expand("file.url", "file.mime")  // projection of N fields
   *     .expand("project")           // multiple distinct refs
   *
   * Whole-row vs projection per ref field:
   *   - Bare ref name (`"file"`) — server emits the full
   *     `sanitize()` projection of the linked row.
   *   - One or more `"file.<field>"` entries — server emits ONLY
   *     `{ id, type, <fields> }`. The id and type are always
   *     present so the frontend can still hydrate a ref-proxy.
   *   - Mixing a bare ref with dotted projections of the same ref
   *     promotes to whole-row (the bare entry wins).
   *
   * The raw id ALWAYS lands in `$file` regardless — the frontend
   * accessor pair `(file, $file)` is the same shape the lazy ref
   * proxy has used since DOL-148. `.expand()` only changes whether
   * the linked row is pre-hydrated, not whether the id is present.
   *
   * Realtime: subscription invalidation is currently **naive** for
   * projected expands. Any change to a linked-row column re-emits
   * to every subscriber that expanded the parent ref, regardless of
   * which fields the subscriber projected. That over-notifies in
   * the projection case (a `blurhash` flip wakes a `file.url`
   * subscriber) but stays correct. Field-aware invalidation is a
   * follow-up (see DOL-1093 open questions).
   *
   * `Model.hydrate` walks the schema; ref-field objects pre-populate
   * the ref-proxy's loaded slot so `asset.file.url` is synchronous
   * (no Suspense throw, no extra HTTP). Field projections come
   * back as a partial linked row — the proxy serves whatever fields
   * the server included and falls through to a lazy `findById` only
   * when the consumer asks for an unprojected field.
   *
   * Validation runs on the backend:
   *   - Bare field (`"file"`) — must exist in `ModelClass.__schema`
   *     as `{ kind: "ref", target }`.
   *   - Dotted field (`"file.url"`) — the `"file"` segment must be
   *     a ref; the `"url"` segment must exist in `target.__schema`.
   *   - Unknown / non-ref field → 400.
   *
   * v1 is one-hop. Nested ref-chaining (`"project.user"` where both
   * are refs) is a follow-up; dot-syntax is reserved for "ref +
   * field projection" right now.
   */
  expand(...fields: string[]): QueryChain<T>;

  // Chainable — aggregates (chainable versions)
  sum(column: string): QueryChain<T>;
  avg(column: string): QueryChain<T>;
  min(column: string): QueryChain<T>;
  max(column: string): QueryChain<T>;
  increment(column: string, amount?: number): QueryChain<T>;
  decrement(column: string, amount?: number): QueryChain<T>;

  // Convenience
  basic(
    limit?: number,
    sort?: string,
    direction?: "asc" | "desc",
    page?: number,
  ): QueryChain<T>;

  // Terminal — execute the query
  find(): Promise<T[]>;
  first(): Promise<T | null>;
  count(): Promise<number>;

  // Introspection — access underlying query builder
  /** @internal Return the underlying query builder (e.g. Knex QueryBuilder). */
  exec(): any;
  /** @internal Create an independent copy of this chain. */
  clone(): QueryChain<T>;

  /**
   * Return a sibling chain whose `.find()` injects
   * `__forceRefresh: true` into the request. The backend's auto-CRUD
   * LIST handler re-executes the cached subscription query against
   * the DB, rebuilds its result map, and emits any drift ops to
   * every subscriber. Used by `useQuery({ poll })` to recover from
   * missed cross-process events. Not part of the public fluent API —
   * call sites should reach for the `poll` option instead.
   *
   * Optional — backends that don't implement realtime can leave it
   * unimplemented; `useQuery` falls back to the plain refetch path
   * via `__forceRefresh` being a no-op server-side.
   *
   * @internal
   */
  withForceRefresh?(): QueryChain<T>;

  /**
   * Return a sibling chain whose `.find()` injects
   * `__subscribe: false` into the request. The backend's auto-CRUD
   * LIST handler skips `QuerySubscriptionManager.subscribe` and
   * returns the result set without a `__queryHash`. The frontend
   * `useQuery` hook uses this to honour `{ subscribe: false }` —
   * static queries that don't need realtime push (frozen historical
   * reports, cold registry rows, etc.). Composable with
   * `withForceRefresh` for the polled-but-static case.
   *
   * Optional — backends that don't implement realtime can leave it
   * unimplemented; the flag is a no-op server-side anyway.
   *
   * @internal
   */
  withSubscribe?(subscribe: boolean): QueryChain<T>;

  // Internal — used by hooks and subscription manager
  /** @internal */ __steps: QueryStep[];
  /** @internal */ __modelType: string;
  /** @internal */ __modelClass: ModelConstructor<T>;
  /** @internal */ __adapter: ModelAdapter;
  /** @internal — true when `.withForceRefresh()` was applied. */
  __forceRefresh?: boolean;
  /** @internal — false when `.withSubscribe(false)` was applied. */
  __subscribe?: boolean;
  /**
   * @internal — ref field names recorded by `.expand(...)`. Used by
   * backend route handlers / the subscription manager to drive
   * `hydrateExpansions` after the SQL query runs. Frontend never
   * reads this; it lives on the chain so the backend can recover
   * the list without re-walking `__steps`.
   */
  __expand?: readonly string[];
}

// ─── Model Adapter ───────────────────────────────────────────────────────────

/**
 * The adapter interface. Decouples Model from persistence.
 *
 * - FrontendAdapter: EventEmitter + transport
 * - BackendAdapter: Knex + PostgreSQL + hooks + pub/sub
 */
export interface ModelAdapter {
  /** Create the data store. Frontend: shallow copy. Backend: plain object. */
  createStore(data: Record<string, any>): Record<string, any>;

  /**
   * Upsert the model's entire current state. No diffing, no dirty
   * tracking — the model carries its full `__data` and (on the
   * backend) an `__isNew` flag that controls hook routing (create vs
   * save).
   */
  save(model: any): Promise<void>;

  /** Delete a model. */
  remove(model: any): Promise<void>;

  /** Fetch a single model by ID. */
  findById<T>(modelClass: ModelConstructor<T>, id: string): Promise<T | null>;

  /** Start a query chain. */
  query<T>(modelClass: ModelConstructor<T>): QueryChain<T>;

  /**
   * Build a scoped query from client-sent QueryStep[] (backend only).
   * Safe replay of __query steps with scope applied first.
   */
  queryFromClient?<T>(
    modelClass: ModelConstructor<T>,
    scope: Record<string, any>,
    rawSteps: QueryStep[] | string | undefined,
  ): QueryChain<T>;

  /** Apply atomic RFC 6902 JSON Patch operations. */
  patch(model: any, ops: PatchOp[]): Promise<void>;
}

export type { PatchOp };

// ─── Chainable Methods ───────────────────────────────────────────────────────

/**
 * The set of query chain methods that are chainable (return a new QueryChain).
 * Shared across lazyQuery, FrontendAdapter, and BackendAdapter to avoid
 * the same 37-element array being duplicated three times.
 */
export const CHAINABLE_METHODS = [
  "select",
  "where",
  "andWhere",
  "orWhere",
  "whereIn",
  "whereNot",
  "whereNotIn",
  "whereNull",
  "whereNotNull",
  "whereBetween",
  "whereRaw",
  "orWhereRaw",
  "orWhereIn",
  "orWhereNull",
  "whereExists",
  "search",
  "orderBy",
  "orderByRaw",
  "groupBy",
  "groupByRaw",
  "having",
  "havingRaw",
  "limit",
  "offset",
  "distinct",
  "distinctOn",
  "join",
  "innerJoin",
  "leftJoin",
  "rightJoin",
  "clearOrder",
  "clearSelect",
  "clearLimit",
  "from",
  "sum",
  "avg",
  "min",
  "max",
  "increment",
  "decrement",
  "expand",
] as const;

// ─── Expand step helpers ─────────────────────────────────────────────────────

const EMPTY_EXPAND: readonly string[] = Object.freeze([]);

/**
 * Collect ref-field projections recorded by `.expand(...)`. Returns
 * the flattened, de-duplicated list of expand specs in the order
 * the client recorded them (stable so the route handler can derive
 * a deterministic subscription hash; see
 * `services/subscriptions.ts`).
 *
 * Specs can be:
 *   - `"file"`           — full linked row inlined.
 *   - `"file.url"`       — single projected field.
 *   - `"file.url", "file.mime"` — multiple fields on the same ref.
 *
 * The route handler reconciles a bare-ref spec against per-field
 * specs on the same ref (bare wins → whole-row).
 *
 * Lives next to `CHAINABLE_METHODS` because step manipulation is
 * pure data — no Knex, no transport. Both the frontend client and
 * the backend route handler import this same function so the
 * frontend-sidecar `__expand` and the route-handler validation
 * agree on what was requested.
 */
export function extractExpandFields(
  steps: QueryStep[] | null | undefined,
): readonly string[] {
  if (!Array.isArray(steps) || steps.length === 0) return EMPTY_EXPAND;
  const out: string[] = [];
  const seen = new Set<string>();
  for (const step of steps) {
    if (step.method !== "expand") continue;
    for (const arg of step.args) {
      if (typeof arg !== "string") continue;
      const trimmed = arg.trim();
      if (!trimmed) continue;
      if (seen.has(trimmed)) continue;
      seen.add(trimmed);
      out.push(trimmed);
    }
  }
  return out.length > 0 ? out : EMPTY_EXPAND;
}

/** Strip every `expand` step from the array. Used by the backend route
 * handler before replaying steps through `queryFromClient` — expand is
 * a metadata projection, not a SQL operation. */
export function stripExpandSteps(
  steps: QueryStep[] | null | undefined,
): QueryStep[] {
  if (!Array.isArray(steps) || steps.length === 0) return [];
  let stripped: QueryStep[] | null = null;
  for (let i = 0; i < steps.length; i++) {
    if (steps[i]!.method === "expand") {
      if (stripped === null) stripped = steps.slice(0, i);
      continue;
    }
    if (stripped !== null) stripped.push(steps[i]!);
  }
  return stripped ?? steps;
}

/**
 * Detect `.orderBy(false)` in a step list. The subscriptions manager
 * reads this to decide whether to compute and emit the `order` field
 * on the wire envelope.
 *
 * Returns `true` when ANY `orderBy` step in the chain was passed
 * `false` (caller opted out of order emission). The last call in
 * the chain doesn't have to be the false one — if any opt-out
 * appears, we honour it.
 */
export function orderEmissionDisabled(
  steps: QueryStep[] | null | undefined,
): boolean {
  if (!Array.isArray(steps) || steps.length === 0) return false;
  for (const step of steps) {
    if (step.method !== "orderBy") continue;
    if (step.args.length === 1 && step.args[0] === false) return true;
  }
  return false;
}
