/**
 * @parcae/model — Adapter Types
 *
 * Defines the adapter interface that decouples Model from persistence.
 * Frontend: Valtio + Socket.IO transport
 * Backend: Knex + PostgreSQL
 */

import type { Operation as PatchOp } from "fast-json-patch";

// ─── Column Types ────────────────────────────────────────────────────────────

/**
 * Primitive column types that map to Postgres column types.
 * These are resolved from TypeScript types via RTTIST at startup.
 */
export type PrimitiveColumnType =
  | "string" // VARCHAR(2048)
  | "text" // TEXT
  | "integer" // INTEGER
  | "number" // DOUBLE PRECISION
  | "boolean" // BOOLEAN
  | "datetime" // TIMESTAMP
  | "json"; // JSONB

/**
 * A column can be a primitive type or a reference to another Model class.
 */
export type ColumnType =
  | PrimitiveColumnType
  | { kind: "ref"; target: ModelConstructor };

/**
 * Schema definition for a model, mapping property names to column types.
 * Generated by the RTTIST schema resolver at startup.
 */
export type SchemaDefinition = Record<string, ColumnType>;

/**
 * Index definition — a single column name or a composite index.
 */
export type IndexDefinition = string | string[];

// ─── Model Constructor ───────────────────────────────────────────────────────

/**
 * The static side of a Model subclass.
 */
export interface ModelConstructor<T = any> {
  type: string;
  path?: string;
  scope?: ModelScope;
  indexes?: IndexDefinition[];
  managed?: boolean;
  __schema?: SchemaDefinition;
  new (adapter: ModelAdapter, data?: Record<string, any>): T;
}

// ─── Scope System ────────────────────────────────────────────────────────────

/**
 * Context passed to scope functions. Contains the authenticated user
 * and request parameters.
 */
export interface ScopeContext {
  user?: { id: string; [key: string]: any } | null;
  params?: Record<string, string>;
  data?: Record<string, any>;
}

/**
 * The result of a scope function. Either:
 * - A query builder modifier function (for read/update/delete/patch)
 * - A data object to merge (for create — e.g. { user: ctx.user.id })
 * - null to deny access
 */
export type ScopeResult = ((qb: any) => any) | Record<string, any> | null;

/**
 * A scope function receives the request context and returns a ScopeResult.
 */
export type ScopeFunction = (ctx: ScopeContext) => ScopeResult;

/**
 * Per-operation scope definitions.
 */
export interface ModelScope {
  read?: ScopeFunction;
  create?: ScopeFunction;
  update?: ScopeFunction;
  delete?: ScopeFunction;
  patch?: ScopeFunction;
}

// ─── Change Tracking ─────────────────────────────────────────────────────────

/**
 * A set of changes to flush to the adapter.
 */
export interface ChangeSet {
  /** Property names that were set via direct assignment */
  updates: string[];
  /** RFC 6902 JSON Patch operations */
  ops: PatchOp[];
  /** Whether this is a new model being created */
  creating: boolean;
}

// ─── Query Chain ─────────────────────────────────────────────────────────────

/**
 * A serializable query step. On the frontend, query chains record steps
 * as these objects and send them to the backend for execution.
 */
export interface QueryStep {
  method: string;
  args: any[];
}

/**
 * Chainable query builder. The generic T flows through to terminal methods.
 *
 * On the backend, each method directly mutates a Knex query.
 * On the frontend, each method records a QueryStep for serialization.
 */
export interface QueryChain<T> {
  // Chainable — filtering
  where(...args: any[]): QueryChain<T>;
  andWhere(...args: any[]): QueryChain<T>;
  orWhere(...args: any[]): QueryChain<T>;
  whereIn(column: string, values: any[]): QueryChain<T>;
  whereNot(...args: any[]): QueryChain<T>;
  whereNotIn(column: string, values: any[]): QueryChain<T>;
  whereNull(column: string): QueryChain<T>;
  whereNotNull(column: string): QueryChain<T>;
  whereBetween(column: string, range: [any, any]): QueryChain<T>;
  whereRaw(query: string, ...bindings: any[]): QueryChain<T>;
  orWhereRaw(query: string, ...bindings: any[]): QueryChain<T>;
  orWhereIn(column: string, values: any[]): QueryChain<T>;
  orWhereNull(column: string): QueryChain<T>;
  whereExists(callback: any): QueryChain<T>;

  // Chainable — ordering & pagination
  orderBy(column: string, direction?: "asc" | "desc"): QueryChain<T>;
  orderByRaw(query: string, ...bindings: any[]): QueryChain<T>;
  limit(count: number): QueryChain<T>;
  offset(count: number): QueryChain<T>;

  // Chainable — selection & grouping
  select(...columns: string[]): QueryChain<T>;
  distinct(...columns: string[]): QueryChain<T>;
  distinctOn(...columns: string[]): QueryChain<T>;
  groupBy(...columns: string[]): QueryChain<T>;
  groupByRaw(query: string, ...bindings: any[]): QueryChain<T>;
  having(...args: any[]): QueryChain<T>;
  havingRaw(query: string, ...bindings: any[]): QueryChain<T>;

  // Chainable — joins
  join(...args: any[]): QueryChain<T>;
  innerJoin(...args: any[]): QueryChain<T>;
  leftJoin(...args: any[]): QueryChain<T>;
  rightJoin(...args: any[]): QueryChain<T>;

  // Chainable — modifiers
  clearOrder(): QueryChain<T>;
  clearSelect(): QueryChain<T>;
  from(table: string): QueryChain<T>;

  // Chainable — aggregates (chainable versions)
  sum(column: string): QueryChain<T>;
  avg(column: string): QueryChain<T>;
  min(column: string): QueryChain<T>;
  max(column: string): QueryChain<T>;
  increment(column: string, amount?: number): QueryChain<T>;
  decrement(column: string, amount?: number): QueryChain<T>;

  // Convenience
  basic(
    limit?: number,
    sort?: string,
    direction?: "asc" | "desc",
    page?: number,
  ): QueryChain<T>;

  // Terminal — execute the query
  find(): Promise<T[]>;
  first(): Promise<T | null>;
  count(): Promise<number>;

  // Internal — used by hooks and subscription manager
  /** @internal */ __steps: QueryStep[];
  /** @internal */ __modelType: string;
  /** @internal */ __modelClass: ModelConstructor<T>;
  /** @internal */ __adapter: ModelAdapter;
  /** @internal */ __debounceMs?: number;
}

// ─── Model Adapter ───────────────────────────────────────────────────────────

/**
 * The adapter interface. Decouples Model from persistence.
 *
 * - FrontendAdapter: Valtio proxy + Socket.IO transport
 * - BackendAdapter: Knex + PostgreSQL + hooks + pub/sub
 */
export interface ModelAdapter {
  /** Create the reactive data store. Frontend: Valtio proxy. Backend: plain object. */
  createStore(data: Record<string, any>): Record<string, any>;

  /** Persist changes (create or update). */
  save(model: any, changes: ChangeSet): Promise<void>;

  /** Delete a model. */
  remove(model: any): Promise<void>;

  /** Fetch a single model by ID. */
  findById<T>(modelClass: ModelConstructor<T>, id: string): Promise<T | null>;

  /** Start a query chain. */
  query<T>(modelClass: ModelConstructor<T>): QueryChain<T>;

  /** Apply atomic RFC 6902 JSON Patch operations. */
  patch(model: any, ops: PatchOp[]): Promise<void>;
}

export type { PatchOp };
