/**
 * ChangeBus — cross-process model-change event bus.
 *
 * The QuerySubscriptionManager is per-process: a write on instance A
 * never reaches a subscriber socket on instance B unless someone fans
 * the event out. This bus is the fan-out. It wraps PubSub so the same
 * code path works in single-process dev (in-memory EventEmitter) and
 * multi-process production (Redis pub/sub).
 *
 * Event shape: `{ table, op, id, requestId, source }`. No `before` or
 * `after` row data — subscribers re-query through scope to get the
 * post-change view, which keeps the wire payload small and dodges the
 * temptation to statically analyze where-clauses on raw row contents.
 *
 * Dedup: hook-path writes carry a freshly-generated `requestId`; the
 * LISTEN/NOTIFY poller emits the same `requestId` (read from the
 * trigger payload's `parcae.request_id`). The bus holds a small TTL
 * map of recently-seen hook requestIds and drops LISTEN emissions
 * that match, so a Parcae-originated write isn't re-dispatched twice.
 *
 * Without LISTEN/NOTIFY enabled, the dedup map is empty and all events
 * pass through.
 */
import { generateId } from "@parcae/model";

import { log } from "../logger";
import type { PubSub } from "./pubsub";

// ─── Types ───────────────────────────────────────────────────────────────────

export type ChangeOp = "insert" | "update" | "delete";
export type ChangeSource = "hook" | "listen";

export interface Change {
  /** Table name (== Model.type pluralized via pluralize()). */
  table: string;
  /** The originating write op. */
  op: ChangeOp;
  /** Row id. */
  id: string;
  /** Per-write tag, generated by the hook path. Used to dedup the LISTEN echo. */
  requestId: string;
  /** Where this Change came from. `"listen"` is dropped on requestId match. */
  source: ChangeSource;
}

export type ChangeListener = (change: Change) => void;

interface ChangeBusOptions {
  /** PubSub instance to publish/subscribe through. Required. */
  pubsub: PubSub;
  /** Redis/in-process channel name. Default `"parcae:change"`. */
  channel?: string;
  /**
   * How long (ms) hook-emitted requestIds stay in the dedup window.
   * LISTEN events arriving within this window with a matching
   * requestId are dropped. Default `5_000`.
   */
  dedupTtlMs?: number;
}

// ─── ChangeBus ───────────────────────────────────────────────────────────────

export class ChangeBus {
  private pubsub: PubSub;
  private channel: string;
  private dedupTtlMs: number;
  /** requestId → expires-at (ms epoch). */
  private dedup = new Map<string, number>();
  private listeners = new Set<ChangeListener>();
  private unsubscribePubsub: (() => void) | null = null;
  private gcTimer: ReturnType<typeof setInterval> | null = null;

  constructor(opts: ChangeBusOptions) {
    this.pubsub = opts.pubsub;
    this.channel = opts.channel ?? "parcae:change";
    this.dedupTtlMs = opts.dedupTtlMs ?? 5_000;

    // Subscribe BEFORE returning so a publish from this very process is
    // delivered back to us (which is what we want — the local subscription
    // manager is itself a listener on the bus).
    this.unsubscribePubsub = this.pubsub.on(this.channel, (raw: unknown) => {
      const change = this._coerce(raw);
      if (!change) return;
      this._handle(change);
    });

    // Cheap GC pass — the dedup map only ever holds entries that
    // expire within `dedupTtlMs`, but the Map is unbounded if writes
    // happen faster than the bus drains them (e.g. backpressure on
    // the Redis SUB connection). 1s cadence keeps the map within
    // ~`dedupTtlMs * writes/sec` entries during steady state.
    this.gcTimer = setInterval(() => this._gc(), 1_000);
    // Don't keep the event loop alive just for this GC.
    if (typeof this.gcTimer.unref === "function") this.gcTimer.unref();
  }

  /**
   * Emit a Change. Hook-path callers should pass `source: "hook"` and a
   * requestId; the poller passes `source: "listen"` and the requestId
   * it parsed from the trigger payload.
   *
   * Hook emissions register the requestId in the dedup window before
   * publishing — that way a LISTEN echo that arrives on the same
   * instance (or a different one) within the window is dropped.
   */
  emit(change: Change): void {
    if (change.source === "hook" && change.requestId) {
      this.dedup.set(change.requestId, Date.now() + this.dedupTtlMs);
    }
    // PubSub.emit publishes to Redis when configured, otherwise routes
    // to the in-process EventEmitter — the local handler we installed
    // in `on(channel, …)` fires uniformly in both modes.
    this.pubsub.emit(this.channel, change);
  }

  /** Register a listener. Returns an unsubscribe function. */
  on(listener: ChangeListener): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }

  /**
   * Generate a fresh request-id. Adapter call sites use this once per
   * write so the LISTEN echo (if any) can be deduplicated.
   *
   * The id is a Parcae-style timestamp-prefixed nanoid via
   * `@parcae/model`'s `generateId`, so the prefix keeps the dedup
   * map sortable in case we ever want to GC by issue-time rather
   * than expiry-time.
   */
  newRequestId(): string {
    return `req_${generateId()}`;
  }

  /** Cleanup — call before disposing the app. */
  close(): void {
    if (this.gcTimer) clearInterval(this.gcTimer);
    this.gcTimer = null;
    this.unsubscribePubsub?.();
    this.unsubscribePubsub = null;
    this.listeners.clear();
    this.dedup.clear();
  }

  // ── Internal ────────────────────────────────────────────────────────

  private _coerce(raw: unknown): Change | null {
    // PubSub round-trips through JSON in the Redis path, so the shape
    // is already plain JSON. In the in-process path the object is
    // forwarded as-is. Either way, defensively validate fields so a
    // malformed publisher can't crash the listener loop.
    if (typeof raw !== "object" || raw === null) return null;
    const c = raw as Record<string, unknown>;
    if (typeof c.table !== "string") return null;
    if (typeof c.id !== "string") return null;
    if (c.op !== "insert" && c.op !== "update" && c.op !== "delete") {
      return null;
    }
    if (c.source !== "hook" && c.source !== "listen") return null;
    const requestId = typeof c.requestId === "string" ? c.requestId : "";
    return {
      table: c.table,
      op: c.op,
      id: c.id,
      requestId,
      source: c.source,
    };
  }

  private _handle(change: Change): void {
    // Drop LISTEN echoes of a hook-path emit we already dispatched.
    // Hook-path emits are never dropped — they're authoritative.
    if (change.source === "listen" && change.requestId) {
      const expiresAt = this.dedup.get(change.requestId);
      if (expiresAt && expiresAt > Date.now()) return;
    }
    for (const listener of this.listeners) {
      try {
        listener(change);
      } catch (err) {
        // A faulty listener should not block the others.
        log.warn(`changeBus: listener threw: ${String(err)}`);
      }
    }
  }

  private _gc(): void {
    const now = Date.now();
    for (const [key, expiresAt] of this.dedup) {
      if (expiresAt <= now) this.dedup.delete(key);
    }
  }

  // ── Test/inspection helpers ─────────────────────────────────────────

  /** @internal */
  get stats() {
    return {
      listeners: this.listeners.size,
      dedupEntries: this.dedup.size,
    };
  }
}
